### PR TITLE
Add LLDB (debug) command

### LINKED ISSUE #125: Create a `spin lldb` similar to `spin gdb`.
Using `gdb` on a mac is an exercise in pain because of SIP and code signing. People will have a much easier time using `lldb` so if possible we should create a new `spin` subcommand for it.

### PR DESCRIPTION
**Pull request by stefanv**
LLDB is the default debugger in Xcode on macOS, but also runs on Linux and Windows. See https://lldb.llvm.org/

Closes #125

/cc @ngoldbaum

### CODE REVIEW

**Comment by ngoldbaum** [comment]
Ping @mtsokol who has a debugger working with numpy on a mac and can test this on MacOS.

**Comment by mtsokol** [comment]
I've just run `spin lldb` with locally built spin and it worked same as with `lldb` directly.

**Comment by stefanv** [comment]
Thanks for the feedback @mtsokol. Does the spin command help simplify your workflow?

**Comment by mtsokol** [comment]
Yes, I think it's more consistent now to use commands `spin test`, `spin ipython` and `spin lldb` for me.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
