### PR TITLE
Allow overriding --prefix in spin build

### LINKED ISSUE #240: "spin build" errors on windows
When I try to use spin to build numpy on windows, I get:

```
meson.build:1:0: ERROR: prefix balue '/usr' must be an absolute path
```

It looks like this is hard-coded in the `build` command. I've never had an issue with it before so no idea why it's problematic now.

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #240

This lets users override --prefix. Right now it's hard-coded, which leads to breakage on windows sometimes.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@stefanv I think your existing windows tests do run on powershell. You can see what shell ana ctions step is running by expanding the input details.

image


So I think the issue isn't powershell so much as how python is set up. I can trigger the problem using a python installed via micromamba and uv on Windows.

**Comment by stefanv** [comment]
We don't actually install to `/usr`, though, that is the prefix used under the `build-install` dir. I think that is in place to make some of the checking work, by having the path names be predictable.

The tests seem happy, though, so perhaps you're right!

**Comment by stefanv** [comment]
> python installed via micromamba and uv on Windows

This is very helpful; I could make a matrix entry for that.

**Comment by ngoldbaum** [comment]
For uv you can do something like this on github actions:

```
    - uses: astral-sh/setup-uv@v3
    - run: |
        uv python install ${{ matrix.version }}
        uv venv --python ${{ matrix.version }}
    - run: |
        .venv\Scripts\activate
        uv pip install some_dependency
        python -m pytest
```

**Comment by ngoldbaum** [comment]
Darn, it looks like simply installing python from uv wasn't enough to trigger it in the spin tests. I'm not sure how to write a test using the existing framework to trigger what I'm seeing with NumPy.

I guess I could add a CI job that just builds NumPy?

I'll leave it up to you, please feel free to push to this PR if you want to adjust things.

**Comment by stefanv** [comment]
Thank you so much, Nathan. I'm out until next week, but will take a look at it then.

**Comment by ngoldbaum** [comment]
OK, I've added a new `--prefix` option to `meson.build`. If I update NumPy's `build` command to match meson's everything works and I'm able to use `spin build --prefix` with numpy. Also added a test.

I also ran into #242, I think it's too easy for commands that projects want to override to go out of sync with upstream improvements.

**Comment by ngoldbaum** [comment]
I also just checked on the Windows system I originally had a problem on - changing the default prefix to `"C:\\"` allows me to build on Windows.

**Comment by ngoldbaum** [comment]
Hi, any chance we can get this reviewed? I tried again today to set up Windows tests for NumPy using `spin` on the free-threaded build using an alternate way to install Python and I hit this issue again, so setting up tests on Windows is currently blocked on this.

**Review by stefanv — APPROVED** [review]

**Pull request merged**
