### PR TITLE
Add a pytest based testing framework and tests for build

### PR DESCRIPTION
**Pull request by ganesh-k13**
### Changes

- [x] Add a pytest based testing framework
- [x] Add tests for
  - [x] `--version`
  - [x] `build`

### Notes
- part of https://github.com/scientific-python/spin/issues/154
- I'll club the relevant commands and raise PRs to not bloat one single big bang PR.
- Additionally, the faster this goes in, we need not maintain tests in two places, i.e. `spin/tests` and `.github/workflows/test.sh `

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks, this is a great start! After merging #159 tomorrow, I'll get this in, and then spend some time porting the tests (unless someone beats me to it!).

**Comment by ganesh-k13** [comment]
Thanks @stefanv! No worries :) I'll try to port all the tests, just wanted to ensure I'm on the right track.

**Comment by stefanv** [comment]
@ganesh-k13 @jarrodmillman Can you take a look? I think this is ready now.

**Comment by ganesh-k13** [comment]
Thanks @stefanv ! I was away for a few weeks.

**Comment by stefanv** [comment]
Thanks for getting this started, @ganesh-k13!

**Pull request merged**
