### PR TITLE
Fix testing for editable and non-editable installs alike

### PR DESCRIPTION
**Pull request by stefanv**
Work to address #209, #203, #204, #208

### CODE REVIEW

**Comment by stefanv** [comment]
@ngoldbaum This should fix the problems with NumPy, hopefully. There's still one problem due to the way NumPy overrides this command, such that `spin test numpy.linalg` does not work (vs `spin test -t numpy.linalg`, which does). It'd be an easy fix on the NumPy side, though.

**Comment by stefanv** [comment]
@jarrodmillman Given that the current test command is broken, I recommend we do this as a point release, but we could also just do a 0.11.

**Comment by ngoldbaum** [comment]
> It'd be an easy fix on the NumPy side, though.

Sounds reasonable. Care to elaborate a little bit?

**Comment by stefanv** [comment]
Sure! The user is supposed to supply tests as `spin test -t test.name`, but as a convenience we also allow `spin test.name`. To detect this case, we check for a single argument (maybe there's a better way, but that's what happens right now), and NumPy modifies the arguments of `spin test foo.bar` to look something like `-m 'not slow' foo.bar`. The simplest fix is to take a single argument test specification and pass it as the `tests` argument, instead of as part of `pytest_args`.

**Comment by ngoldbaum** [comment]
I tried testing this after implementing the suggested change to numpy's spin configuration, but I'm still getting an error trying to do `spin build` on this branch of `spin`:

```
± spin test numpy.linalg
Invoking `build` prior to running tests:
Error: 'NoneType' object has no attribute 'dir_info'; aborting.
```

This is coming from here: https://github.com/scientific-python/spin/blob/b705a480febbe145d461e5a36d9456c9bb13f442/spin/cmds/meson.py#L49

I don't know enough about how `importlib_metadata` works to know why `Distribution.from_name('numpy').origin` is `None` on my system and python install:

```
In [1]: import importlib_metadata

In [2]: print(importlib_metadata.Distribution.from_name('numpy').origin)
None
```

**Comment by stefanv** [comment]
OK, I thought we patched that; let me check why that error is still present for you.

**Comment by stefanv** [comment]
https://github.com/scientific-python/spin/pull/212

**Comment by ngoldbaum** [comment]
See https://github.com/numpy/numpy/pull/26813

**Comment by stefanv** [comment]
That wasn't supposed to close. Reopened as #213

**Pull request closed without merging**
